common: &common
  adapter: postgresql
  username: sample_app
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: myapp_development

test: &test
  <<: *common
  database: myapp_test

production:
  <<: *common
  database: myapp_production
cucumber:
  <<: *test